
// User
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';

export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const SUCCESS_SIGN_OUT = 'SUCCESS_SIGN_OUT';
export const ERROR_SIGN_OUT = 'ERROR_SIGN_OUT';


//Book
export const REQUEST_BOOKS = 'REQUEST_BOOKS';
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';
export const ERROR_RECEIVE_BOOKS = 'ERROR_RECEIVE_BOOKS';
export const REMOVE_BOOK = 'REMOVE_BOOK';
export const RESET_BOOKS = 'RESET_BOOKS';


export const REQUEST_BOOK = 'REQUEST_BOOK';
export const RECEIVE_BOOK = 'RECEIVE_BOOK';
export const ERROR_RECEIVE_BOOK = 'ERROR_RECEIVE_BOOK';
export const RESET_BOOK = 'RESET_BOOK';

export const REQUEST_BOOK_CREATE = 'REQUEST_BOOK_CREATE';
export const SUCCESS_BOOK_CREATE = 'SUCCESS_BOOK_CREATE';
export const ERROR_BOOK_CREATE = 'ERROR_BOOK_CREATE';
export const RESET_BOOK_CREATE = 'RESET_BOOK_CREATE';

export const REQUEST_BOOK_UPDATE = 'REQUEST_BOOK_UPDATE';
export const SUCCESS_BOOK_UPDATE = 'SUCCESS_BOOK_UPDATE';
export const ERROR_BOOK_UPDATE = 'ERROR_BOOK_UPDATE';
export const RESET_BOOK_UPDATE = 'RESET_BOOK_UPDATE';

export const REQUEST_BOOK_DELETE = 'REQUEST_BOOK_DELETE';
export const SUCCESS_BOOK_DELETE = 'SUCCESS_BOOK_DELETE';
export const ERROR_BOOK_DELETE = 'ERROR_BOOK_DELETE';
export const RESET_BOOK_DELETE = 'RESET_BOOK_DELETE';


//Author
export const REQUEST_AUTHORS = 'REQUEST_AUTHORS';
export const RECEIVE_AUTHORS = 'RECEIVE_AUTHORS';
export const ERROR_RECEIVE_AUTHORS = 'ERROR_RECEIVE_AUTHORS';
export const RESET_AUTHORS = 'RESET_AUTHORS';

export const REQUEST_AUTHOR = 'REQUEST_AUTHOR';
export const RECEIVE_AUTHOR = 'RECEIVE_AUTHOR';
export const ERROR_RECEIVE_AUTHOR = 'ERROR_RECEIVE_AUTHOR';
export const RESET_AUTHOR = 'RESET_AUTHOR';
