spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/bookstoredb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
server:
  error:
    include-message: always
    include-stacktrace: never
