elasticsearch:
  address: localhost:9200
  bulk-batch: 2048

threads:
  pool:
    size: 4

spring:
  servlet:
    max-content-length: 50MB
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB